"""changing  order column-2 

Revision ID: 3aff3c217f21
Revises: e718f214c973
Create Date: 2025-03-01 12:42:48.870691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aff3c217f21'
down_revision: Union[str, None] = 'e718f214c973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pdf_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'pdf_url')
    # ### end Alembic commands ###
