"""change the order delivered_at datatype 

Revision ID: 50d8bc6c6c1e
Revises: 04e77eb0c6dc
Create Date: 2025-03-01 15:51:24.560095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50d8bc6c6c1e'
down_revision: Union[str, None] = '04e77eb0c6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivered_at',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivered_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
