"""create table e-commerce

Revision ID: 8a82368a36de
Revises: 
Create Date: 2025-02-27 12:43:36.901303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a82368a36de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_description', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('category_product',
    sa.Column('category_product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_product_name', sa.String(length=255), nullable=True),
    sa.Column('category_product_description', sa.Text(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_product_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('user_type', mysql.TINYINT(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment=' 1 for Active, 0 for Inactive '),
    sa.Column('verification', mysql.TINYINT(), nullable=True, comment='0->not verified 1-verified'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1-active 0-inactive'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('sub_category',
    sa.Column('sub_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_product_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_name', sa.String(length=255), nullable=True),
    sa.Column('sub_category_description', sa.Text(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_product_id'], ['category_product.category_product_id'], ),
    sa.PrimaryKeyConstraint('sub_category_id')
    )
    op.create_table('bill',
    sa.Column('bill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=200), nullable=True),
    sa.Column('bill_address', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('category_product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=True),
    sa.Column('product_discount', sa.Float(), nullable=True),
    sa.Column('product_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.brand_id'], ),
    sa.ForeignKeyConstraint(['category_product_id'], ['category_product.category_product_id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.sub_category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('order_details',
    sa.Column('order_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    op.create_table('productimage',
    sa.Column('productimage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('productimage_url', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('productimage_id')
    )
    op.create_table('wishlist',
    sa.Column('wishlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('wishlist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.drop_table('productimage')
    op.drop_table('order_details')
    op.drop_table('cart')
    op.drop_table('product')
    op.drop_table('bill')
    op.drop_table('sub_category')
    op.drop_table('order')
    op.drop_table('api_token')
    op.drop_table('user')
    op.drop_table('category_product')
    op.drop_table('brand')
    # ### end Alembic commands ###
