"""changing the column wishlist and bill

Revision ID: 9be5dc52e521
Revises: 8a82368a36de
Create Date: 2025-02-27 22:26:29.426900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9be5dc52e521'
down_revision: Union[str, None] = '8a82368a36de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill', 'pdf_url')
    op.drop_column('wishlist', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('bill', sa.Column('pdf_url', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
